export const chatMessages = [
  { id: 1, sender: "Alice", text: "Welcome to WalleTalk!" },
  { id: 2, sender: "Bob", text: "Ready to talk in Web3 style 🚀" },
  { id: 3, sender: "You", text: "Let's get it started 🔐" },
];
export const users = [
  {
    id: 1,
    name: "Elizabeth Olsen",
    role: "Junior Developer",
    avatar: "💁‍♀️",
    status: "online",
    walletAddress: "0x1234567890abcdef1234567890abcdef12345678",
    ensName: "elizabeth.eth",
    nftAvatar: "https://example.com/nft1.png",
  },
  {
    id: 2,
    name: "Gravid Christofer",
    role: "Senior Developer",
    avatar: "🧑‍💻",
    status: "offline",
    walletAddress: "0xabcdef1234567890abcdef1234567890abcdef12",
    ensName: null,
    nftAvatar: null,
  },
  {
    id: 3,
    name: "Chioma Okeke",
    role: "Frontend Developer",
    avatar: "💁‍♀️",
    status: "online",
    walletAddress: "0x7890abcdef1234567890abcdef1234567890abcd",
    ensName: "chioma.crypto",
    nftAvatar: "https://example.com/nft2.png",
  },
  {
    id: 4,
    name: "Obinna Nwachukwu",
    role: "Backend Developer",
    avatar: "🧑‍💻",
    status: "online",
    walletAddress: "0xdef1234567890abcdef1234567890abcdef12345",
    ensName: null,
    nftAvatar: null,
  },
  {
    id: 5,
    name: "Adaora Nwosu",
    role: "Product Designer",
    avatar: "🎨",
    status: "offline",
    walletAddress: "0x4567890abcdef1234567890abcdef1234567890a",
    ensName: "adaora.eth",
    nftAvatar: "https://example.com/nft3.png",
  },
  {
    id: 6,
    name: "Kenechukwu Eze",
    role: "DevOps Engineer",
    avatar: "🛠️",
    status: "online",
    walletAddress: "0xbcdef1234567890abcdef1234567890abcdef123",
    ensName: null,
    nftAvatar: null,
  },
  {
    id: 7,
    name: "Brad Frost",
    role: "Designer",
    avatar: "🎨",
    status: "online",
    walletAddress: "0x234567890abcdef1234567890abcdef12345678",
    ensName: "brad.crypto",
    nftAvatar: "https://example.com/nft4.png",
  },
  {
    id: 8,
    name: "Aarav Mehta",
    role: "Blockchain Analyst",
    avatar: "🧠",
    status: "online",
    walletAddress: "0x567890abcdef1234567890abcdef1234567890b",
    ensName: "aarav.eth",
    nftAvatar: null,
  },
  {
    id: 9,
    name: "Léa Dubois",
    role: "UX Researcher",
    avatar: "🧪",
    status: "online",
    walletAddress: "0x890abcdef1234567890abcdef1234567890abcd",
    ensName: null,
    nftAvatar: "https://example.com/nft5.png",
  },
  {
    id: 10,
    name: "José Ramirez",
    role: "Smart Contract Engineer",
    avatar: "🧱",
    status: "offline",
    walletAddress: "0xcdef1234567890abcdef1234567890abcdef1234",
    ensName: "jose.crypto",
    nftAvatar: null,
  },
  {
    id: 11,
    name: "Zhi Wei Chen",
    role: "Security Specialist",
    avatar: "🔐",
    status: "online",
    walletAddress: "0xef1234567890abcdef1234567890abcdef12345",
    ensName: "zhiwei.eth",
    nftAvatar: "https://example.com/nft6.png",
  },
  {
    id: 12,
    name: "Marcus Johnson",
    role: "DAO Contributor",
    avatar: "👨‍💼",
    status: "online",
    walletAddress: "0x34567890abcdef1234567890abcdef123456789",
    ensName: "marcus.dao",
    nftAvatar: null,
  },
  {
    id: 13,
    name: "Sofia Patel",
    role: "NFT Artist",
    avatar: "🎨",
    status: "offline",
    walletAddress: "0x67890abcdef1234567890abcdef1234567890c",
    ensName: null,
    nftAvatar: "https://example.com/nft7.png",
  },
  {
    id: 14,
    name: "Hiroshi Tanaka",
    role: "DeFi Expert",
    avatar: "💰",
    status: "online",
    walletAddress: "0x90abcdef1234567890abcdef1234567890abcd",
    ensName: "hiroshi.eth",
    nftAvatar: null,
  },
  {
    id: 15,
    name: "Amara Okafor",
    role: "Community Manager",
    avatar: "👩‍💼",
    status: "online",
    walletAddress: "0xabcdef1234567890abcdef1234567890abcdef",
    ensName: "amara.crypto",
    nftAvatar: "https://example.com/nft8.png",
  },
];
export const messages = [
  { sender: "Chioma", text: "Nnoo! I just entered the room 💜" },
  { sender: "Obinna", text: "Chioma, kedu? Did you check the project layout?" },
  {
    sender: "Chioma",
    text: "I did o, but some bugs dey hide like masquerade!",
  },
  { sender: "Adaora", text: "Abeg share the bug list — I go squash them 🐛" },
  {
    sender: "Obinna",
    text: "By the way, our UI slaps! I'm loving the design 🔥",
  },
  {
    sender: "Chioma",
    text: "No be lie. This WalleTalk be like proper Silicon Igbo tech 😎",
  },
  {
    sender: "Aarav",
    text: "Namaste fam! Our smart contract passed all tests 🚀",
  },
  { sender: "Léa", text: "Bonjour team! The UX flow feels très magnifique ✨" },
  {
    sender: "José",
    text: "¡Hola! I’ll optimize gas fees and ping Kene to deploy 🔧",
  },
  {
    sender: "Zhi Wei",
    text: "Security audit completed. We're locked down 🔐✅",
  },
  { sender: "Marcus", text: "Just minted my first NFT on WalleTalk! 🎨" },
  { sender: "Sofia", text: "Anyone up for a token swap? 💸" },
  { sender: "Hiroshi", text: "DeFi yields are looking good this week 📈" },
  { sender: "Amara", text: "Community vote: Should we add voice calls? 🗳️" },
  { sender: "Elizabeth", text: "ENS integration is live! Use your .eth names 🏷️" },
];
export const chatRooms = [
  {
    id: "room123",
    name: "General",
    description: "Daily check-ins & social talk",
    members: 245,
    isTokenGated: false,
  },
  {
    id: "dev456",
    name: "Web3 Devs",
    description: "Smart contracts, wallets, and DApps",
    members: 89,
    isTokenGated: true,
    tokenRequirement: "Hold 1 WTLK token",
  },
  {
    id: "crypto789",
    name: "Crypto Talk",
    description: "Price action, trends, coins",
    members: 156,
    isTokenGated: false,
  },
  {
    id: "nft101",
    name: "NFT Collectors",
    description: "Showcase and trade NFTs",
    members: 78,
    isTokenGated: true,
    tokenRequirement: "Own at least 1 NFT",
  },
  {
    id: "dao202",
    name: "DAO Governance",
    description: "Discuss and vote on proposals",
    members: 67,
    isTokenGated: true,
    tokenRequirement: "DAO member token",
  },
  {
    id: "defi303",
    name: "DeFi Strategies",
    description: "Yield farming and liquidity pools",
    members: 92,
    isTokenGated: false,
  },
];
export const features = [
  {
    icon: "🔐",
    title: "Wallet-Based Login",
    desc: "Secure conversations backed by your crypto identity.",
  },
  {
    icon: "📁",
    title: "File Sharing",
    desc: "Send files, designs, voice notes, and NFTs — no hassle.",
  },
  {
    icon: "🛡️",
    title: "Safety Tools",
    desc: "Moderation, bans, and alerts to keep communities peaceful.",
  },
  {
    icon: "🏷️",
    title: "ENS Integration",
    desc: "Chat with .eth names instead of wallet addresses.",
  },
  {
    icon: "🎨",
    title: "NFT Avatars",
    desc: "Set your profile picture using NFTs you own.",
  },
  {
    icon: "💸",
    title: "Token Transfers",
    desc: "Send crypto directly in chat conversations.",
  },
  {
    icon: "🗳️",
    title: "Token-Gated Rooms",
    desc: "Access exclusive chats by holding specific tokens.",
  },
  {
    icon: "🔒",
    title: "Self-Destruct Messages",
    desc: "Time-limited messages that disappear automatically.",
  },
  {
    icon: "📞",
    title: "Voice & Video Calls",
    desc: "Encrypted wallet-based calls for private communication.",
  },
];

export const stats = [
  { title: "Smart Wallets Connected", value: "2,291" },
  { title: "Rooms Created", value: "842" },
  { title: "UX Rating", value: "4.8/5" },
];

export const testimonials = [
  {
    name: "Chioma Okeke",
    quote: "The chat speed and wallet logic is unlike anything I’ve used.",
  },
  {
    name: "Aarav Mehta",
    quote:
      "I vibe with WalleTalk because it respects developers and our tools.",
  },
  {
    name: "Léa Dubois",
    quote: "Finally, a community that mixes great UX with real-time culture.",
  },
];

export const adminStats = {
  usersOnline: 126,
  messagesToday: 432,
  recentAlerts: [
    "New room created: #Web3 Devs",
    "Alice joined #General",
    "Server maintenance scheduled for 10PM",
  ],
};
